export const conditionMapIdName: Record<string, string> = {
    c1: "SMA10 over SMA50",
    c2: "RSI (Relative Strength Index)",
    c3: "MACD",
    c4: "Stochastic Oscillator",
    c5: "Momentum",
    c6: "ADX (Average Directional Index)",
    c7: "CCI (Commodity Channel Index)",
    c8: "ATR (Average True Range)",
    c9: "SAR (Stop and Reverse)",
    c10: "OBV (On-Balance Volume)",
    c11: "ROC (Rate of Change)",
    c12: "Williams % R",
    c13: "MFI (Money Flow Index)",
    c14: "Chaikin Oscillator",
    c15: "Trix",
    c16: "Keltner Channel",
    c17: "Aroon Oscillator",
    c18: "New 10-Week High",
    c19: "Awesome Oscillator",
    c20: "10-Week High-Low Range",
    c21: "VWAP (Volume Weighted Average Price)",
    c22: "SMA20",
    c23: "SMA50",
    c24: "SMA200",
    c25: "EMA20",
    c26: "EMA50",
    c27: "EMA200",
    c28: "SMA50 over SMA200",
    c29: "EMA50 over EMA200",
    c30: "Chaikin Money Flow",
    c31: "Ease of Movement",
    c32: "Volume Oscillator",
    c33: "Bollinger Bands",
    c34: "Trendline",
    c35: "Fibonacci Retracement Level",
    c36: "Price Action Breakout",
    c37: "Supertrend",
  };
  
  export const tickerMap: Record<string, string> = {
    "ADANIENT.NS": "Adani Enterprises",
    "AXISBANK.NS": "Axis Bank",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "BAJFINANCE.NS": "Bajaj Finance",
    "BEL.NS": "Bharat Electronics",
    "BHARTIARTL.NS": "Bharti Airtel",
    "CIPLA.NS": "Cipla",
    "HCLTECH.NS": "HCL Technologies",
    "HDFCBANK.NS": "HDFC Bank",
    "HEROMOTOCO.NS": "Hero MotoCorp",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "ICICIBANK.NS": "ICICI Bank",
    "INFY.NS": "Infosys",
    "ITC.NS": "ITC",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "LT.NS": "Larsen & Toubro",
    "M&M.NS": "Mahindra & Mahindra",
    "MARUTI.NS": "Maruti Suzuki",
    "NTPC.NS": "NTPC",
    "ONGC.NS": "Oil and Natural Gas Corporation",
    "RELIANCE.NS": "Reliance Industries",
    "SBIN.NS": "State Bank of India",
    "SUNPHARMA.NS": "Sun Pharmaceutical Industries",
    "TATAMOTORS.NS": "Tata Motors",
    "TATASTEEL.NS": "Tata Steel",
    "TCS.NS": "Tata Consultancy Services",
    "TITAN.NS": "Titan Company",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "WIPRO.NS": "Wipro",
    "ANANTRAJ.NS": "Anant Raj",
    "BEML.NS": "BEML",
    "CASTROLIND.NS": "Castrol India",
    "CESC.NS": "CESC",
    "GODFRYPHLP.NS": "Godfrey Phillips",
    "HFCL.NS": "HFCL",
    "PCBL.NS": "PCBL",
    "PEL.NS": "Piramal Enterprises",
    "RADICO.NS": "Radico Khaitan",
    "RAMCOCEM.NS": "Ramco Cements",
    "TATACHEM.NS": "Tata Chemicals",
    "WELSPUNLIV.NS": "Welspun India",
    "ZENSARTECH.NS": "Zensar Technologies",
    "ACC.NS": "ACC",
    "APOLLOTYRE.NS": "Apollo Tyres",
    "ASHOKLEY.NS": "Ashok Leyland",
    "BHARATFORG.NS": "Bharat Forge",
    "BHEL.NS": "Bharat Heavy Electricals",
    "COLPAL.NS": "Colgate-Palmolive (India)",
    "CUMMINSIND.NS": "Cummins India",
    "ESCORTS.NS": "Escorts Kubota",
    "EXIDEIND.NS": "Exide Industries",
    "HINDZINC.NS": "Hindustan Zinc",
    "HINDPETRO.NS": "Hindustan Petroleum Corporation",
    "MFSL.NS": "Max Financial Services",
    "MRF.NS": "MRF",
    "NATIONALUM.NS": "National Aluminium Company",
    "SAIL.NS": "Steel Authority of India",
    "SRF.NS": "SRF",
    "SUPREMEIND.NS": "Supreme Industries",
    "TATACOMM.NS": "Tata Communications",
    "VOLTAS.NS": "Voltas",
  };